name: Build and Deploy Boilerplate-gen-api image

on: [pull_request]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: build and push docker image
        env:
          PROJECT_ID: ${{secrets.PID}}
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev
          docker build -t asia-south1-docker.pkg.dev/$PROJECT_ID/boilerplate-gen-api .
          docker push asia-south1-docker.pkg.dev/$PROJECT_ID/boilerplate-gen-api

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets.PID }}
          REGION: asia-south1
        run: |
          gcloud run deploy boilerplate-gen-api \
            --image asia-south1-docker.pkg.dev/$PROJECT_ID/boilerplate-gen-api \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated
